### ISSUE TITLE
WhatsApp false positives due to obsolete CIDR

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#341]
See https://explorer.ooni.org/measurement/20200216T230231Z_AS11427_2QcLCBIJStNE89Fd8mRD0YNoRAxy5wDNHhUSVJjenmkJ0sEVGZ

Reported by @agrabeli and @lorenzoPrimi

**Comment by hellais** [comment]
Here is another sample measurement which shows the false positive: https://explorer.ooni.org/measurement/20200218T201823Z_AS24757_5zgq4DYv6ady7ZcZOq9JSngkhY49Tj6hIHd81WuM44U6GKB8L7.

It seems that in both these cases what is triggering the anomaly is `whatsapp_endpoints_dns_inconsistent`, which is happening because we can't attribute the resolved IP addresses for the whatsapp endpoints to WhatsApp itself.

This is most likely being caused by the fact that the CIDR list at this point is very stale: https://github.com/measurement-kit/measurement-kit/blob/62d477f085f767bc8235f04ad08dedd32a03afc6/src/libmeasurement_kit/ooni/whatsapp.cpp#L26 and WhatsApp has stopped updating it with fresh data.

I did a whois on the resolved addresses in both of those test results and I see that they both are mapping to AWS.

Maybe a viable hotfix for this problem could be that of checking if the resolved IPs match to AWS infrastructure.

Alternatively we could disable the DNS consistency check altogether and favour not showing false positives in the app and rather defer analysis to a post-processing stage.

**Comment by bassosimone** [comment]
@hellais thanks for researching this. I think we should not release the mobile app until this is fixed in MK (cc: @lorenzoPrimi).

**Comment by bassosimone** [comment]
> Alternatively we could disable the DNS consistency check altogether and favour not showing false positives in the app and rather defer analysis to a post-processing stage.

This strikes me as a good hotfix. Will implement it as soon as I am in front of my computer again 🙄.

**Comment by bassosimone** [comment]
So, I have implemented a workaround in MK as part of https://github.com/measurement-kit/measurement-kit/pull/1915. Because this is annoying and may have data analysis implications, I have also documented it as part of the experiment spec in https://github.com/ooni/spec/pull/178. There are more follow-up actions required from me to move forward this issue, including tagging a new release of Measurement Kit, rebuilding everything, and shipping it. I will reference this issue as the master issue for all these activities, since it's basically the interrupt to which I reacted.

**Comment by bassosimone** [comment]
I'm proceeding to release MK v0.10.10 and to rebuild everything.

**Comment by bassosimone** [comment]
Have rebuilt MK v0.10.10 for Catalina here: https://github.com/measurement-kit/homebrew-measurement-kit/commit/e28d890524fe1634206981470ff52d03052581f3

**Comment by bassosimone** [comment]
Done for Android here: https://github.com/measurement-kit/android-libs/commit/d2b58c8cd861d29ae4d13914f8fefcc3066c5177

**Comment by bassosimone** [comment]
Done for iOS here https://github.com/measurement-kit/mkall-ios/commit/32b76067b0892752bed5d8895e1e563ca70264bb and here https://github.com/measurement-kit/mkall-ios/releases/tag/v0.8.0

**Comment by bassosimone** [comment]
This issue should actually be open. We have implemented a workaround in MK but we have not fixed the real bug, i.e. that we're using an obsolete WhatsApp CIDR.

**Comment by bassosimone** [comment]
This should also be discussed along with plans to improve the IM tests methodology.

**Comment by bassosimone** [comment]
This is no longer an issue: the plan in https://github.com/ooni/probe-engine/issues/740 will fix this
