### ISSUE TITLE
Understand and manage TLS false positives (1/2): recompile LibreSSL et al.

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#769]

**Comment by fadelkon** [comment]
This issue is related with a false positive I observed in Spain for Women on Waves, while monitoring the blocking of Women on Web.

As we can see at [ooni explorer](https://explorer.ooni.org/search?until=2020-07-14&domain=womenonwaves.org&probe_cc=ES&test_name=web_connectivity&since=2020-04-01&until=2020-07-13), at some point between end May and mid June, the tests for Women on Waves website started to return as Anomaly.

However, the censorship situation had not changed, and neither me nor any other mate in spanish nets could verify this "ghost" blocking of WoWaves. In the other hand, the blocking on WoWeb continued without change. Therefore, it appeared as an OONI bug or a Wave's webserver bug.

Peeking into a [measurement](https://explorer.ooni.org/measurement/20200617T192705Z_AS206565_j4UMS5wlfM2yC0Z2SM2DhEX0E4g4T6sTexT85Ak0tHaiZbVXGe?input=https%3A%2F%2Fwomenonwaves.org), we can see that the error is related to the server's TLS certificate, quoting:

> ssl_error: error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed_

However, again, from my up-to-date web browser everything looks in order: all green, no warnings. Find [attached](
[www_womenonwaves_org.crt.gz](https://github.com/ooni/probe-engine/files/4918425/www_womenonwaves_org.crt.gz) the cert I receive.

At the same time, [a test from ssl-labs](https://www.ssllabs.com/ssltest/analyze.html?d=www.womenonwaves.org&hideResults=on) show vulnerability to ROBOT, but maybe more interestingly, some paths of certificate chain that appear expired since... _Sat, 30 May 2020 10:48:38 UTC (1 month and 14 days ago)_ , so, fitting the time frame we set with the ooni probes.

I'm not familiar enough with the PKI to understand this "multiple paths" thing. However, I'm sure you already have enough info to understand the issue.

I reported the ROBOT issue to women on waves. I hope they fix all warnings that SSL labs give apart from the vuln.

**Comment by bassosimone** [comment]
@fadelkon thank you so much for diving into this!

**Comment by bassosimone** [comment]
This is fixed in LibreSSL v3.1.3, which I am recompiling to release new measuring code.

See https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.1.3-relnotes.txt

**Comment by bassosimone** [comment]
I've done some progress in this sprint and I'm gonna finish in the next sprint by doing https://github.com/ooni/probe-engine/issues/809. Thank you again @fadelkon for your help!
